sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
env:
- TOX_ENV=py27_dj18
- TOX_ENV=py34_dj18
- TOX_ENV=py35_dj18
- TOX_ENV=py27_dj19
- TOX_ENV=py34_dj19
- TOX_ENV=py35_dj19
- TOX_ENV=py27_dj110
- TOX_ENV=py34_dj110
- TOX_ENV=py35_dj110
- TOX_ENV=py36_dj110
install:
- pip install tox wheel
script:
- tox -e $TOX_ENV
branches:
  only:
  - master
deploy:
  provider: pypi
  user: peterbe
  password:
    secure: BVm573If1rHaDOzROUmOsHeVQuY6AXLvrSJWqmBN+oezMYOrrHj5WcDtNM/EMbnJ+x1Zpu1fqd02e+CZLOMymjZwvyOh3INA/bEDiQhtGTF6gZ7IMoJImC1r7vt4LgqCiLi3vvQNP7RVhXk0/NrNHkVpjapqd9K/rgeKYZkHVXI=
  on:
    repo: peterbe/django-fancy-cache
  distributions: "sdist bdist_wheel"
