# Based on
# https://pypi.org/project/tox-gh-actions/

---
name: Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # PyPy disabled per issue #69:
        # https://github.com/peterbe/django-fancy-cache/issues/69
        # python-version: [3.7, 3.8, 3.9, "3.10", "pypy-3.8"]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: apt update
        run: sudo apt update
      - uses: niden/actions-memcached@v7
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          sudo apt install libmemcached-dev
      - name: Test with tox
        run: tox -v
